=== YunitaBukra/Ficheros-XML/data/hrscheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="hr_system">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="geography" type="geographyType"/>
        <xs:element name="departments" type="departmentsType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="geographyType">
    <xs:sequence>
      <xs:element name="region" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="region_name" type="xs:string"/>
            <xs:element name="country" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="country_name" type="xs:string"/>
                  <xs:element name="location" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="street_address" type="xs:string" minOccurs="0"/>
                        <xs:element name="postal_code" type="xs:string" minOccurs="0"/>
                        <xs:element name="city" type="xs:string"/>
                        <xs:element name="state_province" type="xs:string" minOccurs="0"/>
                      </xs:sequence>
                      <xs:attribute name="location_id" type="xs:integer" use="required"/>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
                <xs:attribute name="country_id" type="xs:string" use="required"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="region_id" type="xs:integer" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="departmentsType">
    <xs:sequence>
      <xs:element name="department" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="department_name" type="xs:string"/>
            <xs:element name="manager_id" type="xs:integer" nillable="true" minOccurs="0"/>
            <xs:element name="location_id" type="xs:integer"/>
            
            <xs:element name="employees" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="employee" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="first_name" type="xs:string" minOccurs="0"/>
                        <xs:element name="last_name" type="xs:string"/>
                        <xs:element name="email" type="xs:string"/>
                        <xs:element name="phone_number" type="xs:string" minOccurs="0"/>
                        <xs:element name="hire_date" type="xs:date"/>
                        <xs:element name="job_id" type="xs:string"/> <xs:element name="salary" type="xs:decimal" minOccurs="0"/>
                        <xs:element name="commission_pct" type="xs:decimal" minOccurs="0"/>
                        <xs:element name="manager_id" type="xs:integer" minOccurs="0"/>
                        
                        <xs:element name="job_history" minOccurs="0" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="start_date" type="xs:date"/>
                              <xs:element name="end_date" type="xs:date"/>
                              <xs:element name="job_id" type="xs:string"/>
                              <xs:element name="department_id" type="xs:integer"/>
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                        
                      </xs:sequence>
                      <xs:attribute name="employee_id" type="xs:integer" use="required"/>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            
          </xs:sequence>
          <xs:attribute name="department_id" type="xs:integer" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== YunitaBukra/Ficheros-XML/data/hrscheme.xml
<?xml version="1.0"?>
<hr_system
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="hrscheme.xsd">

  <geography>
    <region region_id="1">
      <region_name>Europe</region_name>
      <country country_id="BE">
        <country_name>Belgium</country_name>
      </country>
      <country country_id="CH">
        <country_name>Switzerland</country_name>
        <location location_id="2900">
          <street_address>Rua Frei Caneca 1360</street_address>
          <postal_code>1730</postal_code>
          <city>Geneva</city>
          <state_province>Geneva</state_province>
        </location>
        <location location_id="3000">
          <street_address>Murtenstrasse 921</street_address>
          <postal_code>3095</postal_code>
          <city>Bern</city>
          <state_province>BE</state_province>
        </location>
      </country>
      <country country_id="DE">
        <country_name>Germany</country_name>
        <location location_id="2700">
          <street_address>Schwanthalerstr. 7031</street_address>
          <postal_code>80925</postal_code>
          <city>Munich</city>
          <state_province>Bavaria</state_province>
        </location>
      </country>
      <country country_id="DK">
        <country_name>Denmark</country_name>
      </country>
      <country country_id="FR">
        <country_name>France</country_name>
      </country>
      <country country_id="IT">
        <country_name>Italy</country_name>
        <location location_id="1000">
          <street_address>40-5-12 Laogianggen</street_address>
          <postal_code>190518</postal_code>
          <city>Beijing</city>
          <state_province />
        </location>
        <location location_id="1100">
          <street_address>93091 Calle della Testa</street_address>
          <postal_code>10934</postal_code>
          <city>Venice</city>
          <state_province />
        </location>
      </country>
      <country country_id="NL">
        <country_name>Netherlands</country_name>
        <location location_id="3100">
          <street_address>Pieter Breughelstraat 837</street_address>
          <postal_code>3029SK</postal_code>
          <city>Utrecht</city>
          <state_province>Utrecht</state_province>
        </location>
      </country>
      <country country_id="UK">
        <country_name>United Kingdom</country_name>
        <location location_id="2400">
          <street_address>8204 Arthur St</street_address>
          <postal_code />
          <city>London</city>
          <state_province />
        </location>
        <location location_id="2500">
          <street_address>Magdalen Centre, The Oxford Science Park</street_address>
          <postal_code>OX9 9ZB</postal_code>
          <city>Oxford</city>
          <state_province>Oxford</state_province>
        </location>
        <location location_id="2600">
          <street_address>9702 Chester Road</street_address>
          <postal_code>9629850293</postal_code>
          <city>Stretford</city>
          <state_province>Manchester</state_province>
        </location>
      </country>
    </region>
    <region region_id="2">
      <region_name>Americas</region_name>
      <country country_id="AR">
        <country_name>Argentina</country_name>
      </country>
      <country country_id="BR">
        <country_name>Brasil</country_name>
        <location location_id="2800">
          <street_address>Rua Frei Caneca 1360</street_address>
          <postal_code>01307-002</postal_code>
          <city>Sao Paulo</city>
          <state_province>Sao Paulo</state_province>
        </location>
      </country>
      <country country_id="CA">
        <country_name>Canada</country_name>
        <location location_id="1800">
          <street_address>147 Spadina Ave</street_address>
          <postal_code>M5V 2L7</postal_code>
          <city>Toronto</city>
          <state_province>Ontario</state_province>
        </location>
        <location location_id="1900">
          <street_address>6092 Boxwood St</street_address>
          <postal_code>YSW 9T2</postal_code>
          <city>Whitehorse</city>
          <state_province>Yukon</state_province>
        </location>
      </country>
      <country country_id="MX">
        <country_name>Mexico</country_name>
        <location location_id="3200">
          <street_address>Mariano Escobedo 9991</street_address>
          <postal_code>11932</postal_code>
          <city>Mexico City</city>
          <state_province>Distrito Federal,</state_province>
        </location>
      </country>
      <country country_id="US">
        <country_name>United States of America</country_name>
        <location location_id="1400">
          <street_address>2014 Jabberwocky Rd</street_address>
          <postal_code>26192</postal_code>
          <city>Southlake</city>
          <state_province>Texas</state_province>
        </location>
        <location location_id="1500">
          <street_address>2011 Interiors Blvd</street_address>
          <postal_code>99236</postal_code>
          <city>South San Francisco</city>
          <state_province>California</state_province>
        </location>
        <location location_id="1600">
          <street_address>2007 Zagora St</street_address>
          <postal_code>50090</postal_code>
          <city>South Brunswick</city>
          <state_province>New Jersey</state_province>
        </location>
        <location location_id="1700">
          <street_address>2004 Charade Rd</street_address>
          <postal_code>98199</postal_code>
          <city>Seattle</city>
          <state_province>Washington</state_province>
        </location>
      </country>
    </region>
    <region region_id="3">
      <region_name>Asia</region_name>
      <country country_id="AU">
        <country_name>Australia</country_name>
        <location location_id="2200">
          <street_address>12-98 Victoria Street</street_address>
          <postal_code>2901</postal_code>
          <city>Sydney</city>
          <state_province>New South Wales</state_province>
        </location>
      </country>
      <country country_id="CN">
        <country_name>China</country_name>
        <location location_id="2000">
          <street_address>40-5-12 Laogianggen</street_address>
          <postal_code>190518</postal_code>
          <city>Beijing</city>
          <state_province />
        </location>
      </country>
      <country country_id="IN">
        <country_name>India</country_name>
        <location location_id="2100">
          <street_address>1298 Vileparle (E)</street_address>
          <postal_code>490231</postal_code>
          <city>Bombay</city>
          <state_province>Maharashtra</state_province>
        </location>
      </country>
      <country country_id="JP">
        <country_name>Japan</country_name>
        <location location_id="1200">
          <street_address>2017 Shinjuku-ku</street_address>
          <postal_code>1689</postal_code>
          <city>Tokyo</city>
          <state_province>Tokyo Prefecture</state_province>
        </location>
        <location location_id="1300">
          <street_address>9450 Kamiya-cho</street_address>
          <postal_code>6823</postal_code>
          <city>Hiroshima</city>
          <state_province />
        </location>
      </country>
      <country country_id="ML">
        <country_name>Malaysia</country_name>
      </country>
      <country country_id="SG">
        <country_name>Singapore</country_name>
        <location location_id="2300">
          <street_address>198 Clementi North</street_address>
          <postal_code>540198</postal_code>
          <city>Singapore</city>
          <state_province />
        </location>
      </country>
    </region>
    <region region_id="4">
      <region_name>Middle East and Africa</region_name>
      <country country_id="EG">
        <country_name>Egypt</country_name>
      </country>
      <country country_id="IL">
        <country_name>Israel</country_name>
      </country>
      <country country_id="KW">
        <country_name>Kuwait</country_name>
      </country>
      <country country_id="NG">
        <country_name>Nigeria</country_name>
      </country>
      <country country_id="ZM">
        <country_name>Zambia</country_name>
      </country>
      <country country_id="ZW">
        <country_name>Zimbabwe</country_name>
      </country>
    </region>
  </geography>
  <departments>
    <department department_id="10">
      <department_name>Administration</department_name>
      <manager_id>200</manager_id>
      <location_id>1700</location_id>
      <employees>
        <employee employee_id="200">
          <first_name>Jennifer</first_name>
          <last_name>Whalen</last_name>
          <email>JWHALEN</email>
          <phone_number>515.123.4444</phone_number>
          <hire_date>2003-09-17</hire_date>
          <job_id>AD_ASST</job_id>
          <salary>4400</salary>
          <manager_id>101</manager_id>
          <job_history>
            <start_date>1995-09-17</start_date>
            <end_date>2001-06-17</end_date>
            <job_id>AD_ASST</job_id>
            <department_id>90</department_id>
          </job_history>
          <job_history>
            <start_date>2002-07-01</start_date>
            <end_date>2006-12-31</end_date>
            <job_id>AC_ACCOUNT</job_id>
            <department_id>90</department_id>
          </job_history>
        </employee>
      </employees>
    </department>
    <department department_id="20">
      <department_name>Marketing</department_name>
      <manager_id>201</manager_id>
      <location_id>1800</location_id>
      <employees>
        <employee employee_id="201">
          <first_name>Michael</first_name>
          <last_name>Hartstein</last_name>
          <email>MHARTSTE</email>
          <phone_number>515.123.5555</phone_number>
          <hire_date>2004-02-17</hire_date>
          <job_id>MK_MAN</job_id>
